name: Build and Release Visualization DLL

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Build PSI Solution
        run: msbuild /p:Configuration=Release /p:Platform=x64 /m ./Psi.sln

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: visualization-dll
          path: ./Sources/Visualization/Microsoft.Psi.Visualization.Windows/bin/Release/net472/Microsoft.Psi.Visualization.Windows.dll

  publish:
    name: Publish release
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: visualization-dll

      - name: Generate Random Name
        id: random-name
        run: echo "::set-output name=name::$(openssl rand -hex 4)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.random-name.outputs.name }}
          release_name: Release ${{ steps.random-name.outputs.name }}
          body: |
            This is the release of Visualization DLL.
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./visualization.dll
          asset_name: visualization.dll
          asset_content_type: application/octet-stream
